# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 03caf130f31fce819920e9b5bdadc103db475effc86fbc56a1f9e3160aa4f34636bf5a19c34dc15a8025bfd610cf1f3031123b0e2f064dc2a566241173c2949c

test:
  secret_key_base: 78db53dd95557599b21dcb1b74c135c5f81fc928297f9793068bc8bd9ccccda68443f891c3644811d4b280e013122bf73accd8bd4667188c0fbbeee2a3c62a4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
